### ISSUE TITLE
No dark theme

### ISSUE THREAD

**Issue by Luckey-Elijah** [gunnarsundberg/covid-tracker-dashboard#1]
I launch the impressive looking application, but found there was no dark theme.

Seems that there should be if this needs to a _production-level_ product.

Ideally a toggle in the corner would be cool.

_Edit: `dart` to `dark`_

**Comment by gunnarsundberg** [comment]
Not sure what you mean by "dart theme"

**Comment by Luckey-Elijah** [comment]
A typo, I meant "dark theme".

**Comment by gunnarsundberg** [comment]
Should be fairly simple using [nuxt color mode](https://github.com/nuxt-community/color-mode-module), but it's not a priority at the moment. You can submit a PR if you'd like.
