### ISSUE TITLE
Zoom button and Overlay render on top of side bar

### ISSUE THREAD

**Issue by Luckey-Elijah** [gunnarsundberg/covid-tracker-dashboard#2]
<img width="1040" alt="Screen Shot 2020-07-01 at 12 47 20 PM" src="https://user-images.githubusercontent.com/38171761/86270357-1e3e2100-bb99-11ea-8294-2627a87f91c0.png">
 The `+` and `-`  buttons overlay the side bar menu. Along with the `Outbreak Summary` widget.

**Comment by gunnarsundberg** [comment]
Just made a fix and will close when it's pushed.

**Comment by Luckey-Elijah** [comment]
Is the issue persisting?
